[package]
name = "banjo-keyring"
version = "0.1.0-dev"
authors = ["Matteo Bertucci <matteobertucci2004@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fuser = "0.7"
